language: csharp

solution: MaxMind.Db.sln

before_install:
  - git submodule update --init --recursive
  - nuget install NUnit.Runners -Version 2.6.3 -o packages

script:
  - xbuild MaxMind.Db.sln
  - mono --runtime=v4.0 packages/NUnit.Runners.2.6.3/tools/nunit-console.exe -exclude=BreaksMono ./MaxMind.Db.Test/bin/Debug/MaxMind.Db.Test.dll

sudo: false

notifications:
  email:
    recipients:
      - dev-ci@maxmind.com
    on_success: change
    on_failure: always
