---
language: csharp
solution: MaxMind.Db.sln

env:
  global:
    - MAXMIND_BENCHMARK_DB=$TRAVIS_BUILD_DIR/MaxMind.Db.Benchmark/GeoLite2-City.mmdb
    - MAXMIND_TEST_BASE_DIR=$TRAVIS_BUILD_DIR/MaxMind.Db.Test
    - CONFIGURATION=Release

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 1.0.4
    mono: none
    sudo: required
    env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp1.0
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    dotnet: 1.0.4
    mono: none
    env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp1.0
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 2.0.0
    mono: none
    sudo: required
    env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp2.0
  - os: osx
    osx_image: xcode9 # macOS 10.12
    dotnet: 2.0.0
    mono: none
    env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp2.0
  - os: linux
    dist: trusty # Ubuntu 14.04
    mono: latest
    sudo: false
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    mono: latest

install: git submodule update --init --recursive

script: ./dev-bin/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "Squj/3RvcTEfCK72Jw5Zzdgk9whWZJAP/n7mqD08siCq1uu5ZRZLLGrawYjKPXwkafmX5MCbmqF6pGOtvnupRiHNWkaY4br7hclkqUCerZi5QROuFOKChKTu7lVxzZkU0e/d+0Ujfqb+1VVPm+oahfZKZ/eG61Em3klKo7sEfig=\n"
