---
version: '1.0.{build}'

os: Visual Studio 2015

environment:
  matrix:
    - Configuration: Debug
      Framework: net45
    - Configuration: Release
      Framework: net45
    - Configuration: Debug
      Framework: netcoreapp1.0
    - Configuration: Release
      Framework: netcoreapp1.0

build_script:
  - git submodule update --init --recursive
  - ps: |
      if (gcm dotnet -errorAction SilentlyContinue) {
        echo "Using dotnet '$((gcm dotnet).Path)'"
        dotnet --info
      }
      else {
        echo "dotnet.exe not found"
        exit 1
      }

      # dotnet restore
      dotnet restore

      if($env:Framework -eq "net45") {
        $FrameworkLibsMoniker = "net45"
      } else {
        $FrameworkLibsMoniker = "netstandard1.4"
      }

      # Build projects 
      dotnet build -c $env:Configuration -f $FrameworkLibsMoniker .\MaxMind.Db
      dotnet build -c $env:Configuration -f $env:Framework .\MaxMind.Db.Benchmark
      dotnet build -c $env:Configuration -f $env:Framework .\MaxMind.Db.Test

test_script:
  - ps: |
      # Run tests
      cd .\MaxMind.Db.Test

      dotnet run -f $env:Framework

notifications:
  - auth_token:
      secure: X+ymndzchVeC2LYsehzOt/GEMFfZJeTENeAU9lwNwTuCxBXFJNkuwZLd9joAtHgykHQoYqmEv/nH64+MA6nTlw==
    channel: '#ci'
    on_build_failure: true
    on_build_status_changed: true
    on_build_success: true
    provider: Slack
  - on_build_failure: true
    on_build_status_changed: true
    on_build_success: false
    provider: Email
    subject: 'AppVeyor build {{status}}'
    to:
      - dev-ci@maxmind.com
